### ISSUE TITLE
Update mean_egg_temp_effect to have the winter run specific value 

### ISSUE THREAD

**Issue by ErinCain** [CVPIA-OSC/DSMtemperature#3]
See the Winter Run DSM for details (currently we update mean_egg_temp_effect in cache-data.

**Comment by ergz** [comment]
make it into a dataframe so that we can use it in the load_baseline_data() for each of the models by calling on `$` on the correct column.

**Comment by ErinCain** [comment]
Adding PR for `fallRunDSM`, `springRunDSM`, and `winterRunDSM` to change the input from `DSMtemperature` for `egg_temp_effect`.
